name: tgtg notifications

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 4-6,13-15 * * *'
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          TGTG_USER_ID: ${{ secrets.TGTG_USER_ID }}
          COOKIE: ${{ secrets.COOKIE }}
          TG_BOT_ID: ${{ secrets.TG_BOT_ID }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: python main.py
